### PR TITLE
fix: only add tabIndex when keyboardControls enabled

### LINKED ISSUE #982: Slider frame tabIndex accessibility issues
We've recently had an external accessibility audit on a site built with lots of nuka-carousel. 

An issue they're currently failing us on is that the slider frame container has `tabIndex=0` applied to it - which is considered a fail as it enables the element to receive focus without being interactive.

That sounds logical - but does anyone know why tabIndex was added to that element?

### PR DESCRIPTION
**Pull request by parkersweb**
### Description

Prevents `tabIndex=0` being added to slider-frame when keyboard controls are not enabled. This fixes an accessibility issue whereby the slider-frame was previously focussable even though it was non-interactive when `enableKeyboardControls=false`.

Not sure if this requires additional tests?

Fixes #982

#### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Verified in nextJs sample app that the `tabindex=0` attribute is only present when `enableKeyboardControls=true`.

### CODE REVIEW

File: packages/nuka/src/carousel.tsx [hunk 1]
```diff
@@ -646,7 +646,7 @@ export const Carousel = (rawProps: CarouselProps): React.ReactElement => {
         }}
         aria-label={frameAriaLabel}
         role="region"
-        tabIndex={0}
+        tabIndex={enableKeyboardControls ? 0 : undefined}
```
Comment (fritz-c) [inline packages/nuka/src/carousel.tsx:649]:
```suggestion
        tabIndex={enableKeyboardControls ? 0 : -1}
```

Let's fall back to -1, just so we don't break any existing logic that programmatically focuses on this component.

**Comment by fritz-c** [comment]
Also, there's this item from the PR template checklist that you skipped:
> I have recorded any user-facing fixes or changes with `pnpm changeset`.

That will help us make the next release with your changes.

**Comment by parkersweb** [comment]
thanks @fritz-c  - should be done now!

**Review by fritz-c — APPROVED** [review]
