### PR TITLE
Issue 610: Prevent swipe logic from taking over when no swipe was made

### LINKED ISSUE #610: Carousel not switching slides on emulated mobile devices in Chrome
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
4.5.12

- What version of React are you using?
16.8.4

- What browser are you using?
Chorem 78.0.3904.97

- What machine are you on?
macOS 10.15.1

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

1. Open Chrome Dev Tools and click on `Toggle Device Bar` to emulate a mobile device
2. In your React component add a button which changes the slide index
3. Click the button. 

**Expected behavior:** Carousel should render/swipe to the next slide.
**Actual behavior:** Carousel doesn't switch slides. Only if `swiping` is set to `false`

```javascript
import React, { Component } from "react";
import Carousel from "nuka-carousel";

export default class ExampleComponent extends Component {
  constructor(props, context) {
    super(props, context);
    this.scrollDown = this.scrollDown.bind(this);
    this.state = {
      slideIndex: 0
    };
    this.carouselSettings = {
      withoutControls: true,
      vertical: true,
      disableEdgeSwiping: true,
      // swiping: false, // if this is uncommented then the scrolling down functionality works
      speed: 500,
      afterSlide: slideIndex => {
        this.setState({ slideIndex });
      }
    };
  }

  scrollDown() {
    const { slideIndex } = this.state;
    if (slideIndex === 0) {
      this.setState({ slideIndex: 1 });
    }
  }

  render() {
    const { data } = this.props;
    const { slideIndex } = this.state;

    return (
      <Carousel slideIndex={slideIndex} {...this.carouselSettings}>
        <div className="section-one">
          <img src={data.imgSrc} alt={data.title} title={data.title} />
          <div className="heading-scroll-wrapper">
            <div className="heading-section">
              <h1>{data.title}</h1>
              <h2>{data.subtitle}</h2>
            </div>
            <button className="scroll-btn" onClick={this.scrollDown}>
              Scroll Down
            </button>
          </div>
        </div>
        <div className="section-two">Some content goes here</div>
      </Carousel>
    );
  }
}
```

### PR DESCRIPTION
**Pull request by mariano-formidable**
### Description

This PR prevents swipe logic from running when a swipe of 0 distance (meaning just tapping the screen) has occurred. 

Fixes #610 

#### Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Existing tests pass.  Manually tested.

### Screenshots

The little numbered button under each slide is a button _within_ the carousel that changes the `slideIndex` on click, before they didn't work (on emulated mobile), now they do:
mobile-button

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -561,7 +563,7 @@ export default class Carousel extends React.Component {
           this.previousSlide();
         }
       }
-    } else {
+    } else if (touchLength > 0) {
```
Comment (mariano-formidable) [inline src/index.js]: Super small fix, just making sure when a touch happens, it has some distance before we trigger the `goToSlide` to slide back to the `currentSlide`.

**Comment by sarmeyer** [comment]
works like a charm! Thank you!
