### PR TITLE
Bug/first last partial wrap around

### LINKED ISSUE #194: When displaying more than 1 slide wrapAround doesn't function as one would expect(Re: infinite looping/head to tail)
An infinite wrap around should place the 1st slide at the end of the last slide.. creating an infinite loop. wrapAround when displaying multiple slides should be head to tail.

currently the way the implementation of wrapAround works is if I have 8 total slides, 6 visible and slide 1 slide at a time, it doesn't wrap until the last slide has passed creating a huge area of nothing

broken_head_to_tail

### LINKED ISSUE #324: First and last slide are not displayed when wrapAround is set and slidesToShow is a decimal number
Having the following options set:
```
cellAlign='center'
slidesToShow={1.25}
wrapAround
```
the last slide is not shown when the 1st slide is active:
image

Same applies for the first slide (it's not shown when the last slide is active):
image

The other slides are displayed properly:
image

**How to reproduce the issue:**
Set the following options in the Carousel in the demo app:
```
cellAlign='center'
slidesToShow={1.25}
wrapAround
```

### LINKED ISSUE #340: NEXT button / infinite loop
is there a way to make the NEXT button nonfunctional after the last slide is displayed, because right now my carousel has a bunch of blank slides after the last slide with material. Or have we figured out the infinite loop yet? wrapAround doesn't work like an infinite loop , or it could be those blank slides ?

### PR DESCRIPTION
**Pull request by mariano-formidable**
I'm re-working some of the wrapAround logic so the current slide always has slides positioned before and after to help prevent slides blinking into existence when cycling through them.

This is a PR will closes #324 , closes #194 , closes #340

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -113,11 +113,40 @@ export default class Carousel extends React.Component {
...
+        return shouldUpdate;
+      })(this.props, nextProps, [
+        'cellSpacing',
+        'vertical',
+        'slideWidth',
+        'slideHeight',
+        'heightMode',
+        'slidesToScroll',
+        'slidesToShow'
+      ]);
```
Comment (samwhale) [inline src/index.js]: This is super sweet. I like how it checks if it actually needs to update. easy to manage later too!

File: src/index.js [hunk 2]
```diff
@@ -850,42 +879,54 @@ export default class Carousel extends React.Component {
...
 
-      if (this.state.slideWidth !== 1) {
-        slidesAfter = Math.ceil(
-          (Math.abs(positionValue) - this.state.slideWidth) /
-            this.state.slideWidth
-        );
+      if (direction < 0) {
+        const temp = slidesBefore;
+        slidesBefore = slidesAfter;
+        slidesAfter = temp;
```
Comment (samwhale) [inline src/index.js]: This totally fixes #194 and #340. Good job getting the bigger half of the slides to show in the direction that it's sliding.

**Comment by webfrontzhifei** [comment]
It will blink when the last slide cycles to the first. so does it not work?
